name: ytdl_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
